name: 'web'
port: 8021
user_srv:
  host: '192.168.1.10'
  port: 50051
  name: "user-srv"

jwt:
  key: 'K2Mcm98G%X6xvRJHzT6TQsZg5CWLv6KW'

sms:
  key: ''
  secret: ''

redis:
  host: '192.168.21.135'
  port: 6380
  expire: 15

consul:
  host: '192.168.1.11'
  port: 8500

debug:
  status: true
